FIND_PATH(LUA_INCLUDE_DIR lua.h /usr/include/ /usr/local/include/ /usr/include/lua5.2/)

FIND_LIBRARY(LUA_LIBRARY NAMES lua5.2 PATH /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu/ )

IF (LUA_INCLUDE_DIR AND LUA_LIBRARY)
  SET(LUA_FOUND TRUE)
ENDIF (LUA_INCLUDE_DIR AND LUA_LIBRARY)


IF (LUA_FOUND)
  IF (NOT LUA_FIND_QUIETLY)
    MESSAGE(STATUS "Found lua: ${LUA_LIBRARY}")
  ENDIF (NOT LUA_FIND_QUIETLY)
ELSE (LUA_FOUND)
  IF (LUA_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find lua")
  ENDIF (LUA_FIND_REQUIRED)
ENDIF (LUA_FOUND)